<?php

namespace Daily\DiscountsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CategoryController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Daily\DiscountsBundle\Controller\CategoryController();
        return $instance;
    }
}
